/*
 * Copyright 2025 MobShield Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.mobshield.gradle

import io.mobshield.gradle.internal.CryptoUtils
import java.io.File

data class BuildInfoRequest(
    val expectedSigningCertSha256: String,
    val expectedPackageName: String,
    val expectedInstallers: List<String>,
    val aggressive: Boolean,
    val randomSeedHex: String?,
    val nativeLibraries: List<String>,
)

data class BuildInfoResult(
    val seedHex: String,
    val headerContent: String,
    val inputsFingerprint: String,
)

object BuildInfoGenerator {
    private val internalSymbols = listOf(
        "mobshield_check_root",
        "mobshield_jb_dyld_image_scan",
        "mobshield_hook_frida_port_probe",
        "mobshield_hook_function_prologue_inspect",
        "mobshield_debug_sysctl_ptraced",
    )

    fun generate(request: BuildInfoRequest): BuildInfoResult {
        val seed = resolveSeed(request.randomSeedHex)
        val entropy = CryptoUtils.randomBytes(16, seed)
        val salt = CryptoUtils.randomBytes(16, seed + byteArrayOf(0x01))
        val prologuePlaintext = ByteArray(64) { 0xFF.toByte() }
        val encrypted = CryptoUtils.encryptAesGcm(prologuePlaintext, entropy, salt)
        val nativePayload = request.nativeLibraries.sorted().joinToString("|").toByteArray()
        val nativeHmac = CryptoUtils.hmacSha256Hex(entropy, nativePayload + seed)

        val symbolDefines = buildSymbolDefines(seed)
        val signer = CryptoUtils.normalizeSha256(request.expectedSigningCertSha256)
        val header = buildString {
            appendLine("/* Generated by io.mobshield.personalize. Not reproducible across builds. */")
            appendLine("#ifndef MOBSHIELD_BUILDINFO_H")
            appendLine("#define MOBSHIELD_BUILDINFO_H")
            appendLine()
            appendLine("#define MOBSHIELD_VERSION \"0.1.0\"")
            appendLine("#define MOBSHIELD_BUILD_ID \"${entropy.toHex().take(32)}\"")
            appendLine("#define MOBSHIELD_SELF_CHECK_MAGIC 0x4D534844u")
            appendLine("#define MOBSHIELD_BUILD_ENTROPY \"${entropy.toHex()}\"")
            appendLine("#define MOBSHIELD_EXPECTED_SIGNER_SHA256 \"$signer\"")
            appendLine("#define MOBSHIELD_EXPECTED_PACKAGE \"${request.expectedPackageName}\"")
            appendLine("#define MOBSHIELD_NATIVELIB_HMAC \"$nativeHmac\"")
            appendLine("#define MOBSHIELD_PROLOGUE_KEY_DERIVATION_SALT \"${salt.toHex()}\"")
            appendLine("#define MOBSHIELD_AGGRESSIVE_ANTI_DEBUG ${if (request.aggressive) 1 else 0}")
            appendLine("#define MOBSHIELD_FN_PROLOGUE_CIPHERTEXT_LEN ${encrypted.ciphertext.size}")
            appendLine("static const unsigned char MOBSHIELD_FN_PROLOGUE_NONCE[] = { ${encrypted.nonce.toCArray()} };")
            appendLine("static const unsigned char MOBSHIELD_FN_PROLOGUE_CIPHERTEXT[] = { ${encrypted.ciphertext.toCArray()} };")
            appendLine()
            symbolDefines.forEach { appendLine(it) }
            appendLine()
            appendLine("#endif  // MOBSHIELD_BUILDINFO_H")
        }

        val fingerprint = listOf(
            seed.toHex(),
            signer,
            request.expectedPackageName,
            request.expectedInstallers.joinToString(","),
            request.aggressive.toString(),
            request.nativeLibraries.joinToString(","),
        ).joinToString("|")

        return BuildInfoResult(seedHex = seed.toHex(), headerContent = header, inputsFingerprint = fingerprint)
    }

    fun shouldSkipGeneration(inputsFile: File, headerFile: File, fingerprint: String): Boolean {
        if (!inputsFile.exists() || !headerFile.exists()) {
            return false
        }
        return inputsFile.readText() == fingerprint
    }

    private fun resolveSeed(randomSeedHex: String?): ByteArray {
        if (!randomSeedHex.isNullOrBlank()) {
            val normalized = CryptoUtils.normalizeSha256(randomSeedHex)
            require(normalized.length == 64) { "randomSeed must be 64 hex characters (256 bits)" }
            return normalized.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        }
        return CryptoUtils.randomBytes(32, null)
    }

    private fun buildSymbolDefines(seed: ByteArray): List<String> {
        return internalSymbols.mapIndexed { index, symbol ->
            val suffix = symbolSuffix(seed, index)
            "#define $symbol MOBSHIELD_R_$suffix"
        }
    }

    private fun symbolSuffix(seed: ByteArray, index: Int): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256")
        digest.update(seed)
        digest.update(index.toByte())
        digest.update("mobshield-symbol-v1".toByteArray())
        return digest.digest().copyOf(4).toHex()
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private fun ByteArray.toCArray(): String = joinToString(", ") { "0x%02x".format(it) }
}
